spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: delivery_partner_app
    password: app123!@#
    url: "jdbc:mysql://localhost:3306/delivery_partner?useSSL=false&allowPublicKeyRetrieval=true"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 30001
  role-name: delivery-partner-api

jwt:
  key: fastcampus-education-kotlin-project
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

google:
  map:
    url: "https://maps.googleapis.com/maps/api/geocode/json"